### PR TITLE
new Config Option to determine whether colelctions should be prefixed or not

### PR DESCRIPTION
**Pull request by fdominik**
as discussed in #40 .
However proper testing is still needed.

### CODE REVIEW

**Comment by fdominik** [comment]
So I found that it doesn't work as I expected, let me push some more fixes today and I will let you know when it is ready... The commits should be automatically appended to this Pull Request...

**Comment by arcanefoam** [comment]
Hi,
Any chance you have an obfuscated small example DB to try this?

**Comment by arcanefoam** [comment]
Hi,
I have ran the ClientTest tests with your patch and everything works ok. However, I am wondering if what we really want is "useExistingGraph" rather than "shouldPrefixCollectionNames" (seems to me this more closely describes what the use case is) Further, with "shouldPrefixCollectionNames" the ArangoDBGraph initialisation will fail if you don't create the properties and variables collections. With the "useExistingGraph", it would be more clear that I want to reuse the existing collections and hence this additional required collections could be created for me (instead of exploding in my face).

**Comment by fdominik** [comment]
Well useExistingGraph means that there already exists a graph and you want to reuse it. This is not true in my opinion, you just want to reuse existing collections, but there still will be a new graph created.
So I would maybe prefer "useExistingCollections" or maybe ""shareCollectionsAmongGraphs"?

The true part is, that additional required collections should be created, I will work on that and commit a fix to the PR.

**Comment by arcanefoam** [comment]
Hi,OK I agree we only want to reuse/share existing vertex/edge collections. With that in mind:

In ArangoDBGraph aprox line 580 in the constructor I have this check:
`
if (graph.exists()) {
    this.name = graph.name();
    ArangoDBUtil.checkGraphForErrors(vertexCollections, edgeCollections, relations, graph, options, shouldPrefixCollectionNames);
    ArangoCursor<String> iter = client.getGraphVariablesId(this.name);
    if (iter.hasNext()) {
        this.variables_id = iter.next();
    }
    else {
        throw new ArangoDBGraphException("Existing graph does not have a Variables collection");
    }
}
`
and the `checkGraphForErrors` method verifies that the required collections exist. However, at the moment this only is checked if a graph with the configured name is found in the database. 

Since the proposed flag allows us to reuse/share existing collections, I guess a similar check for these collections would have to happen.

**Comment by fdominik** [comment]
So I've just comited a fix, which I found when testing #38, and now I did a proper testing of following scenarios, with the expected outcome:
* graph doesnt exists, collections don't exist:
  - creates all collections + creates graph
* graph doesnt exists, collections exist:
  - creates graph
* graph doesnt exists, some collections exist:
  - creates missing collections, creates graph
* graph exists, collections don't exit:
  - FAIL on the missing collections
* graph exists, collections exit:
  - works

It behaves the same way as if it would prefix the collections. That means, it fails only if the graph exists but some collections are missing. Which is correct. So if you are getting some errors, just delete the graph.

So now I don't think the check you mentioned in ArangoDBGraph needs any modification, because it works as it is.

What I am still not sure is the final naming of the new Config Option.

- [ ]  useExistingGraph
- [ ]  useExistingCollections
- [x]  shareCollectionsAmongGraphs

I ticked the one I prefer (and additional JavaDoc + Wiki page would be created so that people better understand the behavior).

**Comment by fdominik** [comment]
Hi @arcanefoam I see that you merged some parts of this PR... However I still see that 3 commits aren't part of it. I don't know why, in github UI it seems you did Merge after I pushed them, however in GIT client I see that you merged with beece57 commit.
So maybe cherry-pick these 3 commits would be usefull?
1eb0895
f9fe26a
05fc8c2

Or merging the fdominik/develop branch from my fork should do the trick as well.

**Comment by arcanefoam** [comment]
Hi, yes I am missing those commits because I am working in the vertex properties as well and some big changes in the client that changed some of the ways the prefix flag is used. 

I haven't forgot about you, but as mentioned somewhere these changes are trickier than foreseen ;)

**Comment by arcanefoam** [comment]
As a closing note, the proposed idea has been merged into version 2.0.2, although some major implementation changes were done .

**Pull request merged**
